import React,{useEffect,useState}from'react';
const EVENT=new Date('2026-12-18T19:30:00+04:00').getTime();
const gold='#d4af67';
export default function WeddingInviteDemo(){const[open,setOpen]=useState(false),[rsvp,setRsvp]=useState(false),[left,setLeft]=useState({d:0,h:0,m:0,s:0});useEffect(()=>{const f=()=>{const x=Math.max(0,EVENT-Date.now());setLeft({d:Math.floor(x/864e5),h:Math.floor(x/36e5)%24,m:Math.floor(x/6e4)%60,s:Math.floor(x/1e3)%60})};f();const i=setInterval(f,1000);return()=>clearInterval(i)},[]);
const ornament=<><div className="absolute inset-3 border border-[#d4af67]/45 rounded-[30px]"/><div className="absolute inset-6 border border-[#d4af67]/20 rounded-[24px]"/><div className="absolute top-7 left-1/2 -translate-x-1/2 text-[#d4af67] text-2xl">❦</div></>;
return <div dir="rtl" className="min-h-screen overflow-x-hidden text-[#f8ead4]" style={{fontFamily:'Georgia, serif',background:'#230509'}}>
{!open&&<div className="fixed inset-0 z-50 flex items-center justify-center p-5" style={{background:'radial-gradient(circle at 50% 40%,#6f1622,#250509 70%)'}}><button aria-label="فتح الدعوة" onClick={()=>setOpen(true)} className="relative w-full max-w-[390px] h-[78vh] max-h-[720px] overflow-hidden rounded-[34px] shadow-[0_35px_90px_#0009] border border-[#d4af67]/40 bg-[#6b1420]">
{ornament}<div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(circle at 20% 30%,#fff 0 1px,transparent 2px),radial-gradient(circle at 80% 65%,#d4af67 0 1px,transparent 2px)',backgroundSize:'42px 42px'}}/><div className="absolute inset-y-0 left-0 w-1/2 border-r border-[#d4af67]/20" style={{background:'linear-gradient(110deg,#4b0c15,#7d1c29 55%,#4a0a13)'}}/><div className="absolute inset-y-0 right-0 w-1/2" style={{background:'linear-gradient(250deg,#4b0c15,#7d1c29 55%,#4a0a13)'}}/>
<div className="absolute top-[16%] left-0 right-0 text-center"><div className="text-[10px] tracking-[.45em] text-[#d4af67]">THE WEDDING OF</div><div className="mt-4 text-3xl tracking-wide">مريم <span style={{color:gold}}>&</span> سيف</div></div><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 w-24 h-24 rounded-full flex items-center justify-center border-[3px] border-[#edcf8e] bg-[radial-gradient(circle,#c99b4d,#7b541d)] shadow-[0_0_0_8px_#4a0b14,0_15px_35px_#0008] text-[#3b0a10] text-2xl">M <span className="mx-1 text-sm">✦</span> S</div><div className="absolute bottom-[13%] left-0 right-0 text-center"><div className="text-[#f7dfb5] text-sm">اضغطي على الختم لفتح الدعوة</div><div className="mt-3 text-[9px] tracking-[.35em] text-[#d4af67]/70">TAP TO UNVEIL</div></div></button></div>}
<section className="relative min-h-screen flex items-center justify-center px-6 py-24 text-center overflow-hidden" style={{background:'radial-gradient(circle at 50% 25%,#861f2e 0,#4c0c15 48%,#220508 100%)'}}>{ornament}<div className="absolute -top-20 -left-20 w-72 h-72 rounded-full bg-[#b72c3c]/20 blur-3xl"/><div className="relative max-w-xl"><div className="text-[#d4af67] text-xl mb-7">❦</div><p className="text-[10px] tracking-[.35em] text-[#d4af67] mb-7">TOGETHER WITH THEIR FAMILIES</p><p className="text-sm opacity-75 mb-5">بكل الحب والامتنان، نتشرف بدعوتكم لمشاركتنا ليلة العمر</p><h1 className="text-6xl md:text-8xl leading-[1.2]">مريم <span className="block text-[#d4af67] text-3xl my-2">&</span> سيف</h1><div className="flex items-center justify-center gap-4 my-8"><span className="w-16 h-px bg-[#d4af67]/50"/><span className="text-[#d4af67]">✦</span><span className="w-16 h-px bg-[#d4af67]/50"/></div><p className="text-lg">الجمعة • 18 ديسمبر 2026</p><p className="text-xs tracking-[.25em] text-[#d4af67] mt-3">MUSCAT • OMAN</p><div className="grid grid-cols-4 gap-2 mt-12">{[['يوم',left.d],['ساعة',left.h],['دقيقة',left.m],['ثانية',left.s]].map(([l,v])=><div key={String(l)} className="py-5 rounded-t-full border border-[#d4af67]/35 bg-[#2c060a]/35"><div className="text-2xl text-[#f6dfb5]">{v}</div><div className="text-[9px] mt-2 text-[#d4af67]">{l}</div></div>)}</div></div></section>
<section className="relative px-6 py-28 text-center bg-[#f1e4d3] text-[#4c1017] overflow-hidden"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-transparent via-[#b78b43] to-transparent"/><div className="max-w-xl mx-auto"><div className="text-[#a57735] text-2xl">❦</div><p className="text-[10px] tracking-[.4em] mt-4 text-[#9b743b]">THE CELEBRATION</p><h2 className="text-4xl mt-5 mb-7">موعدٌ مع الفرح</h2><p className="leading-8 opacity-75">وجودكم بيننا هو أجمل تفاصيل ليلتنا. نتشرف بمشاركتكم فرحتنا وبداية حكايتنا.</p><div className="mt-12 border border-[#b78b43]/45 p-2"><div className="border border-[#b78b43]/25 px-6 py-10"><div className="text-xs text-[#9b743b] tracking-[.2em]">FRIDAY • 18 DECEMBER</div><h3 className="text-3xl mt-5">قصر البستان</h3><p className="mt-3 text-sm opacity-65">الاستقبال 7:30 مساءً • الحفل 8:00 مساءً</p><a href="https://maps.google.com/?q=Al+Bustan+Palace+Muscat" target="_blank" rel="noreferrer" className="inline-block mt-8 px-8 py-3 bg-[#5d121b] text-[#f4dfb9] text-sm">الوصول إلى القصر</a></div></div></div></section>
<section className="relative py-28 px-6 text-center" style={{background:'linear-gradient(180deg,#4b0b13,#250508)'}}><div className="max-w-md mx-auto"><div className="text-[#d4af67] text-2xl">✦</div><p className="text-[10px] tracking-[.35em] text-[#d4af67] mt-4">YOUR PRESENCE IS OUR GIFT</p><h2 className="text-4xl mt-5">شاركونا ليلة العمر</h2><p className="mt-5 opacity-70 leading-7">نرجو تأكيد الحضور قبل 5 ديسمبر 2026</p>{!rsvp?<button onClick={()=>setRsvp(true)} className="mt-9 px-10 py-4 border border-[#d4af67] text-[#f3d9aa] bg-[#7a1824]/30">تأكيد الحضور</button>:<div className="mt-9 border border-[#d4af67]/45 p-7 text-[#f5dfb7]">تم تأكيد حضوركم ♡<div className="text-[9px] tracking-[.3em] mt-2 opacity-60">RSVP DEMO</div></div>}</div></section>
<footer className="py-14 text-center bg-[#180305] border-t border-[#d4af67]/20"><div className="text-[#d4af67] text-2xl">M <span className="text-xs mx-2">✦</span> S</div><div className="text-[9px] tracking-[.35em] mt-3 opacity-55">18 • 12 • 2026</div></footer></div>}
